# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoublyLinkedList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoublyLinkedList
	pod 'SwiftyAWS', :git => 'https://github.com/apeguero24/SwiftyAWS.git'

  target 'DoublyLinkedListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
